// Utility functions for exporting data

export function exportToCSV(data: any[], filename: string) {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  // Get headers from the first object
  const headers = Object.keys(data[0]);
  
  // Create CSV content
  let csvContent = headers.join(',') + '\n';
  
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header];
      // Handle nested objects
      if (typeof value === 'object' && value !== null) {
        return JSON.stringify(value).replace(/,/g, ';');
      }
      // Escape commas and quotes
      return `"${String(value).replace(/"/g, '""')}"`;
    });
    csvContent += values.join(',') + '\n';
  });

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// PDF Export using browser print functionality
export function exportToPDF(title: string, content: string, _filename: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow pop-ups to export PDF');
    return;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          padding: 40px;
          color: #1f2937;
          line-height: 1.6;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #3b82f6;
        }
        .header h1 {
          color: #1e40af;
          font-size: 28px;
          margin-bottom: 8px;
        }
        .header .date {
          color: #6b7280;
          font-size: 14px;
        }
        .section {
          margin-bottom: 30px;
        }
        .section h2 {
          color: #374151;
          font-size: 18px;
          margin-bottom: 15px;
          padding-bottom: 8px;
          border-bottom: 1px solid #e5e7eb;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 15px;
        }
        th, td {
          padding: 12px;
          text-align: left;
          border: 1px solid #e5e7eb;
        }
        th {
          background-color: #f3f4f6;
          font-weight: 600;
          color: #374151;
        }
        tr:nth-child(even) {
          background-color: #f9fafb;
        }
        .stat-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
          margin-bottom: 30px;
        }
        .stat-card {
          background: #f3f4f6;
          padding: 20px;
          border-radius: 8px;
          text-align: center;
        }
        .stat-card .label {
          font-size: 14px;
          color: #6b7280;
          margin-bottom: 8px;
        }
        .stat-card .value {
          font-size: 28px;
          font-weight: 700;
          color: #1e40af;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          font-size: 12px;
          color: #9ca3af;
        }
        .status-active { color: #059669; font-weight: 600; }
        .status-returned { color: #6b7280; }
        .status-overdue { color: #dc2626; font-weight: 600; }
        .fine-unpaid { color: #dc2626; font-weight: 600; }
        .fine-paid { color: #059669; }
        @media print {
          body { padding: 20px; }
          .stat-grid { grid-template-columns: repeat(2, 1fr); }
        }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        <p>Generated by Library Management System on ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.print();
    printWindow.close();
  };
}

// Generate PDF content for borrow records
export function exportBorrowRecordsToPDF(records: any[], stats?: any) {
  const statsHtml = stats ? `
    <div class="stat-grid">
      <div class="stat-card">
        <div class="label">Total Records</div>
        <div class="value">${records.length}</div>
      </div>
      <div class="stat-card">
        <div class="label">Active Borrows</div>
        <div class="value">${records.filter(r => r.status === 'active').length}</div>
      </div>
      <div class="stat-card">
        <div class="label">Overdue</div>
        <div class="value">${records.filter(r => r.status === 'overdue').length}</div>
      </div>
    </div>
  ` : '';

  const tableRows = records.map(record => `
    <tr>
      <td>${record.user?.name || 'Unknown'}</td>
      <td>${record.book?.title || 'Unknown'}</td>
      <td>${new Date(record.borrowedAt).toLocaleDateString()}</td>
      <td>${new Date(record.dueDate).toLocaleDateString()}</td>
      <td>${record.returnedAt ? new Date(record.returnedAt).toLocaleDateString() : '-'}</td>
      <td class="status-${record.status}">${record.status.toUpperCase()}</td>
      <td class="${record.finePaid ? 'fine-paid' : 'fine-unpaid'}">
        ${record.fineAmount ? '$' + record.fineAmount + (record.finePaid ? ' ✓' : '') : '-'}
      </td>
    </tr>
  `).join('');

  const content = `
    <div class="header">
      <h1>📚 Library Borrow Records Report</h1>
      <p class="date">Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    ${statsHtml}
    <div class="section">
      <h2>Borrow Records</h2>
      <table>
        <thead>
          <tr>
            <th>User</th>
            <th>Book</th>
            <th>Borrowed</th>
            <th>Due Date</th>
            <th>Returned</th>
            <th>Status</th>
            <th>Fine</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
    </div>
  `;

  exportToPDF('Borrow Records Report', content, 'borrow_records');
}

// Generate PDF content for books inventory
export function exportBooksToPDF(books: any[]) {
  const statsHtml = `
    <div class="stat-grid">
      <div class="stat-card">
        <div class="label">Total Titles</div>
        <div class="value">${books.length}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Copies</div>
        <div class="value">${books.reduce((sum, b) => sum + b.totalCopies, 0)}</div>
      </div>
      <div class="stat-card">
        <div class="label">Available</div>
        <div class="value">${books.reduce((sum, b) => sum + b.availableCopies, 0)}</div>
      </div>
    </div>
  `;

  const tableRows = books.map(book => `
    <tr>
      <td>${book.title}</td>
      <td>${book.author}</td>
      <td>${book.isbn}</td>
      <td>${book.totalCopies}</td>
      <td>${book.availableCopies}</td>
      <td>${book.totalCopies - book.availableCopies}</td>
    </tr>
  `).join('');

  const content = `
    <div class="header">
      <h1>📖 Library Books Inventory</h1>
      <p class="date">Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    ${statsHtml}
    <div class="section">
      <h2>Books List</h2>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Total</th>
            <th>Available</th>
            <th>Borrowed</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
    </div>
  `;

  exportToPDF('Books Inventory', content, 'books_inventory');
}

// Generate PDF for dashboard stats
export function exportDashboardStatsToPDF(stats: any) {
  const content = `
    <div class="header">
      <h1>📊 Library Dashboard Report</h1>
      <p class="date">Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    <div class="stat-grid">
      <div class="stat-card">
        <div class="label">Total Books</div>
        <div class="value">${stats.totalBooks || 0}</div>
      </div>
      <div class="stat-card">
        <div class="label">Available Books</div>
        <div class="value">${stats.availableBooks || 0}</div>
      </div>
      <div class="stat-card">
        <div class="label">Borrowed Books</div>
        <div class="value">${stats.borrowedBooks || 0}</div>
      </div>
      <div class="stat-card">
        <div class="label">Overdue Books</div>
        <div class="value">${stats.overdueBooks || 0}</div>
      </div>
      <div class="stat-card">
        <div class="label">Total Users</div>
        <div class="value">${stats.totalUsers || 0}</div>
      </div>
      <div class="stat-card">
        <div class="label">Active Borrows</div>
        <div class="value">${stats.activeBorrows || 0}</div>
      </div>
    </div>
  `;

  exportToPDF('Dashboard Report', content, 'dashboard_stats');
}

export function exportBorrowRecordsToCSV(records: any[]) {
  const exportData = records.map(record => ({
    'User Name': record.user?.name || 'Unknown',
    'User Email': record.user?.email || 'N/A',
    'Book Title': record.book?.title || 'Unknown',
    'Book Author': record.book?.author || 'N/A',
    'Borrowed Date': new Date(record.borrowedAt).toLocaleDateString(),
    'Due Date': new Date(record.dueDate).toLocaleDateString(),
    'Returned Date': record.returnedAt ? new Date(record.returnedAt).toLocaleDateString() : 'Not Returned',
    'Status': record.status,
    'Fine Amount': record.fineAmount ? `$${record.fineAmount}` : '$0',
    'Fine Paid': record.finePaid ? 'Yes' : 'No',
  }));

  exportToCSV(exportData, 'borrow_records');
}

export function exportBooksToCSV(books: any[]) {
  const exportData = books.map(book => ({
    'Title': book.title,
    'Author': book.author,
    'ISBN': book.isbn,
    'Description': book.description,
    'Total Copies': book.totalCopies,
    'Available Copies': book.availableCopies,
    'Borrowed Copies': book.totalCopies - book.availableCopies,
    'Created At': new Date(book.createdAt).toLocaleDateString(),
  }));

  exportToCSV(exportData, 'books_inventory');
}

export function exportDashboardStats(stats: any) {
  const exportData = [
    { 'Metric': 'Total Books', 'Value': stats.totalBooks },
    { 'Metric': 'Available Books', 'Value': stats.availableBooks },
    { 'Metric': 'Borrowed Books', 'Value': stats.borrowedBooks },
    { 'Metric': 'Overdue Books', 'Value': stats.overdueBooks },
    { 'Metric': 'Total Users', 'Value': stats.totalUsers },
    { 'Metric': 'Active Borrows', 'Value': stats.activeBorrows },
  ];

  exportToCSV(exportData, 'dashboard_stats');
}
